### PR TITLE
Adding basic checkstyle/spotbug config

### PR DESCRIPTION
**Pull request by jenspapenhagen**
adding basic config files
adding plugin in pom.xml for reports/build

### CODE REVIEW

**Comment by thegeekyasian** [comment]
The checkstyle.xml looks incompatible with IntelliJ, might have issues with contributors struggling to import config.

Can you share the source of the file where, alternatively we can consider the [spring java formatting](https://github.com/spring-io/spring-javaformat/blob/main/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml) as well.

WDYT?

**Comment by jenspapenhagen** [comment]
Hello,
this was only a basic version. The one from spring is far better.
Lets take this.

**Comment by thegeekyasian** [comment]
> Hello, this was only a basic version. The one from spring is far better. Lets take this.

Thank you @jenspapenhagen! Lets do it. Can you please replace the file with the [spring checkstyle](https://github.com/spring-io/spring-javaformat/blob/main/spring-javaformat/spring-javaformat-checkstyle/src/main/resources/io/spring/javaformat/checkstyle/spring-checkstyle.xml) and push the changes please?

**Comment by jenspapenhagen** [comment]
Hallo, 
i have replace the basic config with the config from spring checkstlye.

Thank you for your time and I look forward to your reply.

**Comment by thegeekyasian** [comment]
Closing due to inactivity.

**Pull request closed without merging**
